version: '3.9'

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=commerce
  # redis:
  #   image: redis:alpine
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"
    volumes:
      - ./:/engine

volumes:
  db_data:
